// Generated by CoffeeScript 1.6.2
(function() {
  window.taskData = [
    {
      title: 'Clean bathroom'
    }, {
      title: 'Eat breakfast'
    }, {
      title: 'Cook bacon'
    }, {
      title: 'Buy puppy'
    }
  ];

}).call(this);
